# Defines a sequence of stages to execute
stages:
  train:
    # The command DVC executes for this stage
    cmd: python train.py
    
    # Dependencies (deps): If any of these files change, the stage must rerun.
    deps:
      - train.py
      - data/data.csv
    metrics:
      - model/metrics.json

    
    # Outputs (outs): These files are produced by the stage and are automatically versioned by DVC.
    outs:
      - model/simple_dnn_model.h5
    
    # NEW: Define which file contains plot data
    plots:
      # Plot 1: Loss over Epochs
      - model/simulated_history.json: 
          x: epoch
          y: loss
          title: 'Training Loss over Epochs'
          template: linear
      
      # Plot 2: Accuracy over Epochs (using the same file)
      - model/simulated_history.json:
          x: epoch
          y: accuracy
          title: 'Training Accuracy over Epochs'
          template: linear